#fail pipeline
name: example07
on: [push]
jobs:
    Test1:
        runs-on: ubuntu-latest
        steps: 
            - run: |
                # echo "::error intentional error::Missing semi colon"
                exit 1
                echo "::summary 100 resources created::Missing semi colon"